# Generated by Django 5.0 on 2023-12-14 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_orderitem_transaction_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='transaction_id',
        ),
    ]
