# Generated by Django 5.0 on 2023-12-14 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_remove_shippingaddress_transaction_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='transaction_id',
        ),
    ]
