# Generated by Django 5.0 on 2023-12-14 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_product_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
    ]
