# Generated by Django 5.0 on 2023-12-14 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_shippingaddress_email_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer',
            table='Superuser',
        ),
    ]
