# Generated by Django 5.0 on 2023-12-14 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_customer_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer',
            table=None,
        ),
    ]
